### PR TITLE
add local cluster domain+port

### PR DESCRIPTION
**Pull request by benaadams**

### CODE REVIEW

**Comment by weidazhao** [comment]
Hi Ben, thanks for making the change. I've merged the change into dotnetcli. Running Connect-ServiceFabricCluster without localhost:19000 should just work with unsecure clusters with default settings though. What error did you see?

**Comment by benaadams** [comment]
Gives a `The object is closed` error

```
PS D:\AgeOfAscent\SF> Connect-ServiceFabricCluster
WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service...
WARNING: Failed to connect Failover Manager Service, Attempting to contact FMM...
False
Connect-ServiceFabricCluster : The object is closed.
At line:1 char:1
+ Connect-ServiceFabricCluster
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricObjectClosedException
    + FullyQualifiedErrorId : CreateClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster
```

**Comment by benaadams** [comment]
Ahhh... needed new ps window rather than one I had been working in - can revert?

**Comment by weidazhao** [comment]
Yep, new ps window will work. I will keep the fix since it's clearer in the readme to show where to deploy the app. Thanks!

**Pull request merged**
